import type { SiteContent, PortfolioProject, ServicePackage, MediaItem } from "../src/types.js";

export const DEFAULT_SITE_CONTENT: SiteContent = {
  brandName: "B2bfiy",
  phone: "+880 1712-345678",
  email: "hello@b2bfiy.com",
  socials: {
    facebook: "https://facebook.com/b2bfiy",
    instagram: "https://instagram.com/b2bfiy",
    linkedin: "https://linkedin.com/company/b2bfiy",
    whatsapp: "+8801712345678",
  },
  hero: {
    badge: "PREMIER DIGITAL GROWTH AGENCY IN DHAKA",
    title: "We Build High-Converting Websites, Graphics & Viral Reels",
    highlight: "Engineered For Rapid Business Growth.",
    description:
      "Partner with Dhaka's dedicated digital growth engine. We combine modern full-stack web architecture, conversion-focused graphic branding, and high-retention video production to turn casual visitors into loyal paying customers.",
    trustText: "Trusted by 50+ scaling businesses, e-commerce stores, restaurants, and medical clinics.",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
  },
  stats: [
    { id: "stat-1", value: "98%", label: "Client Satisfaction Rate" },
    { id: "stat-2", value: "50+", label: "Completed Projects" },
    { id: "stat-3", value: "3.5x", label: "Average ROI Multiplier" },
    { id: "stat-4", value: "24/7", label: "Active Project Support" },
  ],
  whyChooseUs: [
    {
      title: "Transparent Pricing, Zero Hidden Fees",
      description: "Clear upfront project quotes and predictable monthly retainer tiers with no sudden surcharges.",
    },
    {
      title: "Ultra-Fast Delivery Cycles",
      description: "Standard business websites live within 7–10 days; high-retention social creatives turned around in 24–48 hours.",
    },
    {
      title: "Dedicated Full-Service Team",
      description: "One cohesive agency replacing five fragmented freelancers—expert developers, designers, video editors, and managers.",
    },
    {
      title: "Data-Driven Conversion Focus",
      description: "Every UI layout, color contrast, and video hook is scientifically structured to maximize sales and customer inquiries.",
    },
  ],
  partners: [
    { id: "partner-1", name: "E-Commerce Brand" },
    { id: "partner-2", name: "Restaurant Group" },
    { id: "partner-3", name: "Local Retailer" },
    { id: "partner-4", name: "Dental Clinic" },
    { id: "partner-5", name: "Tech Startup" },
  ],
  testimonials: [
    {
      id: "t1",
      name: "Tanvir Ahmed",
      role: "Founder, Luxe Fashion BD",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      text: "B2bfiy transformed our online store. Our conversion rate jumped by 140% within the first month after the redesign! Their attention to UX and mobile speed is world-class.",
      rating: 5,
    },
    {
      id: "t2",
      name: "Dr. Farhana Rahman",
      role: "Director, Care Dental Clinic",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
      text: "Their monthly social media management and high-quality reel production brought consistent new patient appointments every single week. Best digital marketing investment we have made.",
      rating: 5,
    },
    {
      id: "t3",
      name: "Sabbir Hossain",
      role: "CEO, TechNova Solutions",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      text: "Incredible development speed and pixel-perfect design. They built our SaaS landing funnel ahead of schedule and perfectly responsive across all mobile screens.",
      rating: 5,
    },
  ],
  about: {
    badge: "About B2bfiy",
    title: "The Dedicated Creative & Growth Engine For Your Business",
    description:
      "We are a team of expert creators, engineers, and marketers aligned to construct professional corporate web platforms, designs, and reels to help brands scale up.",
    missionTitle: "Bridging High-Fidelity Creative Quality and Affordable Predictability",
    missionDesc1:
      "Managing five separate freelance contracts is chaotic. One delivers slow code, another misses graphic styles, and a third stops replying during launch. B2bfiy was founded in Dhaka to establish a single reliable, professional creative team that business owners can delegate to.",
    missionDesc2:
      "We leverage modern technology, custom design systems, and cinematic short-form frameworks to elevate small brands, medical clinics, restaurants, and startups globally into trustworthy digital icons.",
    coreValues: [
      {
        title: "Results-First Execution",
        desc: "We don't prioritize vanity likes or useless visits. We build high-performance pipelines engineered to attract paying customers.",
      },
      {
        title: "Absolute Transparency",
        desc: "No hidden setup costs, unexpected fees, or secret markups. Everything is communicated and priced upfront clearly.",
      },
      {
        title: "Speed & Communication",
        desc: "Our teams coordinate via modern communication panels to answer questions within minutes and deliver designs on time.",
      },
    ],
    founders: [
      {
        emoji: "👨‍💻",
        role: "Co-Founder & CTO",
        name: "Senior Fullstack Engineer",
        description: "Engineers modern, responsive layouts, web portals, and commerce funnels.",
      },
      {
        emoji: "🎨",
        role: "Co-Founder & Creative Director",
        name: "Visual Identity Director",
        description: "Directs social post styling guidelines, packaging, and cinematic reel templates.",
      },
    ],
  },
  footerDesc:
    "We help businesses build a powerful digital presence through high-converting websites, professional graphic design, engaging video content, and complete social media management.",
  copyright: "© 2026 B2bfiy. All rights reserved.",
  privacyPolicy: {
    lastUpdated: "July 19, 2026",
    introduction:
      "B2bfiy (“we,” “our,” or “us”) respects your privacy. This document outlines how we collect, process, and safeguard the information you provide when using our digital agency website, requesting free audits, or ordering monthly creative services.",
    informationCollect:
      "When you interact with our forms, we collect the following:\n\n• Contact Parameters: Full Name, email address, WhatsApp contact number.\n• Business Information: Company Name, existing website or Facebook page URL.\n• Project Guidelines: Desired service models, message texts, or audit contexts.",
    howWeProcess:
      "We process your submitted leads to:\n\n• Analyze your online representation and deliver the Free Digital Audit document.\n• Coordinate project deliverables and pricing quotes via email/WhatsApp.\n• Dispatch periodic performance updates and billing statements to monthly partners.",
    security:
      "We apply server-side encryption protocols and database protection firewalls to prevent unauthorized access, alteration, or data leaks. We do not sell or lease your business handles, email directories, or WhatsApp numbers to third-party marketing brokers.",
    contact:
      "If you have any questions or require your lead history removed from our administrative console database, please contact us directly at hello@b2bfiy.com.",
  },
  terms: {
    lastUpdated: "July 19, 2026",
    scope:
      "By subscribing to B2bfiy monthly retainers or ordering custom website developments, you agree to coordinate with our project directors on layout requirements, content copy, or video edits on a regular basis.",
    billing:
      "Monthly growth retainers (Starter, Growth, Premium) require upfront payment at the start of each billing cycle month. Project-based custom web developments are split into milestone payments (typically 50% deposit and 50% upon final production approval).",
    ipOwnership:
      "Upon complete clearance of billing invoices, the client receives 100% full intellectual property ownership of all finalized custom websites, graphics, logos, layouts, and cinematic reel files. B2bfiy retains the right to display the finalized items in our public portfolio collection unless explicitly requested otherwise in writing.",
    cancellation:
      "Monthly subscription retainers can be cancelled or modified by providing a 7-day written notice before the next billing cycle. We do not provide prorated refunds for active design cycles once assets are delivered.",
    contact:
      "These terms shall be governed by applicable commercial laws. For official legal service notices, please email hello@b2bfiy.com.",
  },
  serviceImages: {
    webDev: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=600&q=80",
    graphic: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80",
    video: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    social: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=600&q=80",
  },
};

export const DEFAULT_PORTFOLIOS: PortfolioProject[] = [
  {
    id: "p1",
    title: "Luxe Fashion - High-Converting E-Commerce Store",
    slug: "luxe-fashion-ecommerce-store",
    clientName: "Luxe Fashion BD",
    category: "Website Development",
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    ],
    liveUrl: "https://example.com/luxe",
    projectDate: "June 2026",
    shortDescription: "Custom responsive e-commerce web platform engineered for instant checkout and high mobile conversion rates.",
    fullDescription: "Luxe Fashion needed a modern, ultra-fast online shopping portal that could handle high-traffic seasonal campaigns while ensuring frictionless 1-click checkout on mobile devices.",
    clientChallenge: "High cart abandonment rates on mobile and sluggish page loads exceeding 4.5 seconds on their previous platform.",
    ourSolution: "Built a headless React/Tailwind frontend backed by high-performance APIs, automated CDN asset caching, and a streamlined 2-step checkout funnel.",
    workProcess: [
      "1. Comprehensive UX audit of existing cart bottlenecks",
      "2. Mobile-first wireframes and high-fidelity Figma prototypes",
      "3. Modern React web development with image optimization",
      "4. Performance tuning achieving sub-1.2s load times on 4G networks",
      "5. A/B testing checkout flows to maximize purchase completion",
    ],
    projectResult: "Cart abandonment dropped by 42% and mobile conversion rate surged by +140% in the first 30 days post-launch.",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Node.js", "PostgreSQL"],
    tags: ["E-Commerce", "Web Development", "Conversion Rate Optimization"],
    featured: true,
    published: true,
  },
  {
    id: "p2",
    title: "Care Dental Clinic - Patient Appointment Booking Portal",
    slug: "care-dental-clinic-portal",
    clientName: "Care Dental Specialists",
    category: "Website Development",
    thumbnail: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80",
    ],
    liveUrl: "https://example.com/care-dental",
    projectDate: "May 2026",
    shortDescription: "Modern medical practice portal with direct WhatsApp consultation integration and automated appointment scheduling.",
    fullDescription: "A clean, clinical, and reassuring medical portal designed to build patient trust and provide one-tap appointment requests for dental treatments.",
    clientChallenge: "Manual phone bookings were overwhelmed during peak hours, and patients struggled to understand treatment pricing.",
    ourSolution: "Designed a clean responsive website with interactive treatment guides, transparent fee calculators, and automated WhatsApp/email booking confirmation.",
    workProcess: [
      "1. Stakeholder interviews with clinic doctors and reception staff",
      "2. Visual branding update with serene medical color palette",
      "3. Custom appointment request form with WhatsApp API webhook",
      "4. Local SEO optimization for Dhaka neighborhood search queries",
    ],
    projectResult: "Direct online appointment bookings increased by +210%, freeing up 15+ hours weekly for clinic reception.",
    technologies: ["React", "Tailwind CSS", "WhatsApp Cloud API", "Vite"],
    tags: ["Medical", "Web Development", "Lead Generation"],
    featured: true,
    published: true,
  },
  {
    id: "p3",
    title: "Aura Skincare - Complete Brand Identity & Packaging Design",
    slug: "aura-skincare-brand-identity",
    clientName: "Aura Organics",
    category: "Graphic Design",
    thumbnail: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",
    ],
    projectDate: "April 2026",
    shortDescription: "Minimalist luxury brand identity, cosmetic packaging labels, and unified digital social media creative kit.",
    fullDescription: "Aura Organics required an upscale, eco-conscious visual identity for their premium botanical skincare line entering retail and direct-to-consumer markets.",
    clientChallenge: "Competing with established multinational cosmetic brands on retail shelves and Instagram feeds with inconsistent visuals.",
    ourSolution: "Created a bespoke geometric logo mark, botanical color palette, foil-stamped product box mockups, and 30+ ready-to-post social media templates.",
    workProcess: [
      "1. Competitive visual audit of international clean beauty brands",
      "2. Logo design iterations and custom typographic wordmark",
      "3. 3D packaging mockups with print-ready vector dielines",
      "4. Comprehensive 40-page brand guidelines handbook",
    ],
    projectResult: "Aura successfully secured shelf placement in 12 premium retail outlets and grew their Instagram followers to 25k within 60 days.",
    technologies: ["Adobe Illustrator", "Photoshop", "Figma", "Blender 3D"],
    tags: ["Branding", "Graphic Design", "Packaging", "Social Media"],
    featured: true,
    published: true,
  },
  {
    id: "p4",
    title: "Viral TikTok & Reels Video Editing - 5M+ Organic Views",
    slug: "viral-tiktok-reels-editing-series",
    clientName: "FitCore Nutrition & Gym",
    category: "Video Editing",
    thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    ],
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    projectDate: "March 2026",
    shortDescription: "High-retention short-form video editing with animated subtitles, dynamic zooms, sound design, and hook engineering.",
    fullDescription: "A series of 20 viral workout and nutrition breakdown clips produced for TikTok, Instagram Reels, and YouTube Shorts to drive supplement sales.",
    clientChallenge: "Raw gym footage suffered from low watch time (under 4 seconds) and failed to convert viewers into website clicks.",
    ourSolution: "Applied psychological retention editing: 2-second visual pattern interrupts, animated kinetic captions, sound effects, and clear CTA end screens.",
    workProcess: [
      "1. Script hook optimization and pacing roadmap",
      "2. High-speed multi-cam trimming and color grading",
      "3. Sound design layering (SFX, risers, custom voice leveling)",
      "4. Animated kinetic captions with highlighted keyword typography",
    ],
    projectResult: "Over 5.4 Million organic views generated across platforms, resulting in 1,200+ direct supplement orders.",
    technologies: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve", "CapCut Pro"],
    tags: ["Video Editing", "Reels", "TikTok", "Short-Form"],
    featured: true,
    published: true,
  },
];

export const DEFAULT_PACKAGES: ServicePackage[] = [
  // Monthly Growth Retainers
  {
    id: "pkg-m1",
    type: "monthly",
    title: "STARTER MONTHLY GROWTH",
    price: "৳12,000 / $120",
    period: "Month",
    isPopular: false,
    features: [
      "12 High-Quality Social Media Graphics",
      "4 High-Retention Reels / Shorts Videos",
      "Complete Monthly Content Calendar",
      "Targeted Hashtag & Caption Copywriting",
      "Facebook & Instagram Page Management",
      "Dedicated Project Manager",
      "Weekly Performance Report",
    ],
    deliveryTime: "Ongoing (Monthly Delivery)",
    ctaText: "Choose Starter Plan",
    published: true,
  },
  {
    id: "pkg-m2",
    type: "monthly",
    title: "GROWTH PRO RETAINER",
    price: "৳25,000 / $240",
    period: "Month",
    isPopular: true,
    features: [
      "20 Premium Social Media Graphics",
      "8 Viral Reels / TikTok Video Edits",
      "Monthly Website Maintenance & Security",
      "Ad Creative Design & Copywriting",
      "Omnichannel Posting (FB, IG, LinkedIn)",
      "Priority 24/7 WhatsApp Support",
      "Monthly Growth & Analytics Strategy Call",
    ],
    deliveryTime: "Ongoing (Monthly Delivery)",
    ctaText: "Choose Growth Pro",
    published: true,
  },
  {
    id: "pkg-m3",
    type: "monthly",
    title: "ENTERPRISE ELITE SUITE",
    price: "৳45,000 / $420",
    period: "Month",
    isPopular: false,
    features: [
      "30 Full-Brand Social Media Graphics",
      "16 Cinematic Viral Video Edits & Motion Graphics",
      "Complete Website Feature Updates & Speed Tuning",
      "Meta Ads & Google Ads Campaign Creatives",
      "Community Management & Inquiry Routing",
      "Dedicated Senior Designer & Developer Team",
      "Real-Time Analytics Dashboard & Weekly Strategy Calls",
    ],
    deliveryTime: "Ongoing (Monthly Delivery)",
    ctaText: "Choose Enterprise Elite",
    published: true,
  },

  // Website Development Packages
  {
    id: "pkg-w1",
    type: "website",
    title: "Starter Business Website",
    price: "৳15,000 / $150",
    period: "Project",
    isPopular: false,
    features: [
      "Up to 5 Custom Responsive Pages",
      "Mobile & Tablet Optimized Layout",
      "Contact Form with Direct WhatsApp Integration",
      "Google Search Console & Basic SEO Setup",
      "High-Speed CDN Hosting Configuration",
      "1 Month Free Technical Support",
    ],
    deliveryTime: "7–10 Business Days",
    ctaText: "Order Starter Website",
    published: true,
  },
  {
    id: "pkg-w2",
    type: "website",
    title: "E-Commerce Conversion Store",
    price: "৳35,000 / $330",
    period: "Project",
    isPopular: true,
    features: [
      "Complete E-Commerce Product Catalog (Up to 100 Products)",
      "Instant 1-Click Mobile Checkout Funnel",
      "bKash, Nagad, Card & SSLCommerz Payment Gateway",
      "Inventory & Order Management Dashboard",
      "Meta Pixel, GA4 & Conversion API Setup",
      "3 Months Free Ongoing Maintenance",
    ],
    deliveryTime: "12–16 Business Days",
    ctaText: "Order E-Commerce Store",
    published: true,
  },
  {
    id: "pkg-w3",
    type: "website",
    title: "Custom Web Application / SaaS",
    price: "৳65,000 / $620",
    period: "Project",
    isPopular: false,
    features: [
      "Full-Stack Custom Architecture (React, Node, PostgreSQL)",
      "User Authentication & Role-Based Access Control",
      "Custom Database Schemas & REST/GraphQL APIs",
      "Interactive Dashboards & Analytics Reporting",
      "Automated Email & SMS Notifications",
      "6 Months Dedicated SLA Support",
    ],
    deliveryTime: "20–30 Business Days",
    ctaText: "Discuss Custom Application",
    published: true,
  },

  // Graphic Design Packages
  {
    id: "pkg-g1",
    type: "graphic",
    title: "Essential Branding Kit",
    price: "৳8,000 / $80",
    period: "Project",
    isPopular: false,
    features: [
      "3 Custom Logo Concepts + Unlimited Minor Revisions",
      "Full Vector Source Files (AI, EPS, SVG, PNG)",
      "Brand Color Palette & Typography Guidelines",
      "Social Media Profile & Cover Banner Kit",
      "Business Card & Letterhead Design",
    ],
    deliveryTime: "3–5 Business Days",
    ctaText: "Order Branding Kit",
    published: true,
  },
  {
    id: "pkg-g2",
    type: "graphic",
    title: "Social Media Creative Pack (15 Posts)",
    price: "৳12,000 / $115",
    period: "Project",
    isPopular: true,
    features: [
      "15 High-Converting Social Media Banners",
      "Consistent Brand Visual Style Guide",
      "Figma / Photoshop Source Files Included",
      "Carousel Infographic Multi-Slides",
      "Engaging Ad Promotional Banners",
    ],
    deliveryTime: "5–7 Business Days",
    ctaText: "Order Creative Pack",
    published: true,
  },

  // Video Editing Packages
  {
    id: "pkg-v1",
    type: "video",
    title: "Reels & Shorts Starter Pack (8 Videos)",
    price: "৳10,000 / $95",
    period: "Project",
    isPopular: false,
    features: [
      "8 Vertical Videos (Under 60 Seconds)",
      "High-Retention Kinetic Captions & Subtitles",
      "Dynamic Zoom Cuts & Sound FX Layering",
      "Color Correction & Audio Noise Cleanup",
      "Optimized for TikTok, IG Reels & YouTube Shorts",
    ],
    deliveryTime: "4–6 Business Days",
    ctaText: "Order Reels Starter",
    published: true,
  },
  {
    id: "pkg-v2",
    type: "video",
    title: "Viral Social Video Suite (16 Videos)",
    price: "৳18,000 / $170",
    period: "Project",
    isPopular: true,
    features: [
      "16 High-Retention Vertical Reels / Shorts",
      "Custom Motion Graphics & 2D Animated Titles",
      "Hook Engineering & Pacing Optimization",
      "Background Music Licensing & Sound Design",
      "2 Revision Rounds per Video",
    ],
    deliveryTime: "7–10 Business Days",
    ctaText: "Order Viral Video Suite",
    published: true,
  },
];

export const DEFAULT_MEDIA_ITEMS: MediaItem[] = [
  {
    id: "m1",
    name: "Luxe Fashion Ecommerce Mockup",
    url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    category: "mockup",
  },
  {
    id: "m2",
    name: "Medical Clinic UI Mockup",
    url: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80",
    category: "mockup",
  },
  {
    id: "m3",
    name: "Skincare Packaging Branding",
    url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    category: "graphic",
  },
  {
    id: "m4",
    name: "Fitness Video Thumbnail",
    url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
    category: "video",
  },
  {
    id: "m5",
    name: "Workspace Office Setup",
    url: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80",
    category: "photo",
  },
];
